PQ, PV, REF, NONE = 1, 2, 3, 4

BUS_I, BUS_TYPE, PD, QD, GS, BS, BUS_AREA, VM, VA, BASE_KV, ZONE, VMAX, VMIN = range(13)
LAM_P, LAM_Q, MU_VMAX, MU_VMIN = range(13, 17)

GEN_BUS, PG, QG, QMAX, QMIN, VG, MBASE, GEN_STATUS, PMAX, PMIN = range(10)
PC1, PC2, QC1MIN, QC1MAX, QC2MIN, QC2MAX = range(10, 16)
RAMP_AGC, RAMP_10, RAMP_30, RAMP_Q, APF = range(16, 21)
MU_PMAX, MU_PMIN, MU_QMAX, MU_QMIN = range(21, 25)

F_BUS, T_BUS, BR_R, BR_X, BR_B, RATE_A, RATE_B, RATE_C, TAP, SHIFT, BR_STATUS = range(11)
ANGMIN, ANGMAX = range(11, 13)
PF, QF, PT, QT = range(13, 17)
MU_SF, MU_ST, MU_ANGMIN, MU_ANGMAX = range(17, 21)

MODEL, STARTUP, SHUTDOWN, NCOST, COST = range(5)
PW_LINEAR, POLYNOMIAL = 1, 2

BUS_COLS, GEN_COLS, BRANCH_COLS = 13, 21, 13
BUS_COLS_OPF, GEN_COLS_OPF, BRANCH_COLS_PF, BRANCH_COLS_OPF = 17, 25, 17, 21

RATINGS = {"A": RATE_A, "B": RATE_B, "C": RATE_C}
